---
sidebar: sidebar 
permalink: scpivs44_download_the_snapcenter_plug-in_for_vmware_vsphere_ova_open_virtual_appliance.html 
keywords:  
summary: È possibile scaricare il file .ova per il plug-in SnapCenter per VMware vSphere dal sito del supporto NetApp. 
---
= Scarica il plug-in SnapCenter per VMware vSphere OVA (appliance virtuale aperta)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile scaricare `.ova` File per il plug-in SnapCenter per VMware vSphere dal sito di supporto NetApp.

Il `.ova` Il file include un set di microservizi per la protezione dei dati di macchine virtuali e datastore, che vengono eseguiti dal plug-in VMware di SnapCenter. Una volta completata l'implementazione, tutti i componenti vengono installati su una macchina virtuale Linux nel proprio ambiente.

.Fasi
. Accedere al NetApp Support Site ( https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^]).
. Dall'elenco dei prodotti, selezionare *plug-in SnapCenter per VMware vSphere*, quindi fare clic sul pulsante *Scarica ultima release*.
. Scarica il plug-in SnapCenter per VMware vSphere `.ova` file in qualsiasi posizione.

